"""Constants for the 2N Intercom integration."""

DOMAIN = "CVM"
MANUFACTURER = "Stewart"
MODEL = "CVM"
EVENT = "CVM_event"

CVM_PRESETS_ASPECT = "cvmpresetar"
CVM_PRESETS_POSITION = "cvmpresetpos"

CVM_CONNECT_TIMEOUT = 20
CVM_LOGIN_TIMEOUT = 5
CVM_PORT = 23
CVM_MIN_COMMAND_INTERVAL = 1
CVM_CALIBRATE_TIMEOUT = 20